import STAGES, { STAGE_LIST } from './stages.js';
import { CHARACTER_ROLES, CHARACTER_ROLE_LIST, RELATIONSHIP_TYPES, RELATIONSHIP_TYPE_LIST } from './roles.js';
import { 
  JOB_STATUSES, 
  JOB_STATUS_LIST, 
  DOCUMENT_STATUSES, 
  DOCUMENT_STATUS_LIST,
  CONTINUITY_SEVERITIES,
  CONTINUITY_SEVERITY_LIST,
  CONTINUITY_STATUSES,
  CONTINUITY_STATUS_LIST
} from './job-status.js';
import { USER_ROLES, USER_ROLES_LIST, USER_STATUSES, USER_STATUSES_LIST } from './user-roles.js';
import { BOOK_STATUSES, BOOK_STATUSES_LIST, BOOK_TEMPLATES, BOOK_TEMPLATES_LIST, BOOK_ACCENTS } from './book.js';
import { TERMS_VERSION, RIGHTS_STATEMENT } from './terms.js';
import {
  FEATURES,
  FEATURE_LIST,
  FEATURE_ACCESS_MODES,
  FEATURE_ACCESS_MODES_LIST,
  FEATURE_ACCESS_MATRIX,
  getFeatureAccessMode,
} from './feature-access.js';

export {
  STAGES,
  STAGE_LIST,
  CHARACTER_ROLES,
  CHARACTER_ROLE_LIST,
  RELATIONSHIP_TYPES,
  RELATIONSHIP_TYPE_LIST,
  JOB_STATUSES,
  JOB_STATUS_LIST,
  DOCUMENT_STATUSES,
  DOCUMENT_STATUS_LIST,
  CONTINUITY_SEVERITIES,
  CONTINUITY_SEVERITY_LIST,
  CONTINUITY_STATUSES,
  CONTINUITY_STATUS_LIST,
  USER_ROLES,
  USER_ROLES_LIST,
  USER_STATUSES,
  USER_STATUSES_LIST,
  BOOK_STATUSES,
  BOOK_STATUSES_LIST,
  BOOK_TEMPLATES,
  BOOK_TEMPLATES_LIST,
  BOOK_ACCENTS,
  TERMS_VERSION,
  RIGHTS_STATEMENT,
  FEATURES,
  FEATURE_LIST,
  FEATURE_ACCESS_MODES,
  FEATURE_ACCESS_MODES_LIST,
  FEATURE_ACCESS_MATRIX,
  getFeatureAccessMode,
};

